[package]
name = "rustapp"
edition = "2024"

[dependencies]
critical-section = { version = "1.2.0", features = ["restore-state-bool"] }
embedded-alloc = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
